# Generated by Django 3.0.5 on 2020-04-13 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 3, 54, 32, 661236), verbose_name='date published'),
        ),
    ]
