# Generated by Django 2.1.7 on 2020-04-16 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200414_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 2, 8, 5, 941066), verbose_name='date published'),
        ),
    ]
