# Generated by Django 2.1.7 on 2020-04-16 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200417_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 3, 35, 3, 655855), verbose_name='date published'),
        ),
    ]
