# Generated by Django 2.1.7 on 2020-04-20 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200417_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 1, 1, 11, 385927), verbose_name='date published'),
        ),
    ]
