# Generated by Django 2.1.7 on 2020-04-20 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200421_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 1, 1, 51, 893936), verbose_name='date published'),
        ),
    ]
