# Generated by Django 2.1.7 on 2020-05-02 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200422_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 19, 36, 1, 655269), verbose_name='date published'),
        ),
    ]
